openapi: 3.0.1
info:
  title: DataSet Management API
  description: DataSet Management API
  version: 0.0.1
servers:
  - url: 'https://api.liveramp.com/data_set_management'
tags:
  - name: Dataset / Field
    description: '(subresource) '
paths:
  '/v1/datasets/{parentId}/fields':
    post:
      tags:
        - Dataset / Field
      operationId: Create Field
      description: Create a new Field
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset--FieldInput'
      responses:
        '201':
          description: Field created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: ''
                    type: number
      parameters:
        - in: path
          name: parentId
          description: Id of parent Dataset
          required: true
          schema:
            type: number
    get:
      tags:
        - Dataset / Field
      operationId: List Dataset--Fields
      description: Find existing Fields
      parameters:
        - in: query
          name: offset
          description: Offset of the record (starting from 0) to include in the response.
          schema:
            type: number
            default: 0
        - in: query
          name: limit
          description: >-
            Number of records to return. If unspecified, 10 records will be
            returned. Maximum value for limit can be 100
          schema:
            type: number
            default: 10
            maximum: 100
        - in: query
          name: id
          description: ''
          required: false
          schema:
            type: number
        - in: query
          name: enabled
          description: ''
          required: false
          schema:
            type: boolean
        - in: path
          name: parentId
          description: Id of parent Dataset
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Fields retrieved successfully
          headers:
            X-Total-Count:
              description: Total number of records in the data set.
              schema:
                type: number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset--FieldMultiResponse'
  '/v1/datasets/{parentId}/fields/{id}':
    get:
      tags:
        - Dataset / Field
      operationId: Get 1 Dataset--Field
      description: Get a Field
      responses:
        '200':
          description: Field retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset--FieldOutput'
      parameters:
        - in: path
          name: id
          required: true
          description: ''
          schema:
            type: number
        - in: path
          name: parentId
          description: Id of parent Dataset
          required: true
          schema:
            type: number
    put:
      tags:
        - Dataset / Field
      operationId: Modify a Dataset--Field
      description: Add values to a Field
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset--FieldMutable'
      responses:
        '200':
          description: Field modified successfully
      parameters:
        - in: path
          name: id
          required: true
          description: ''
          schema:
            type: number
        - in: path
          name: parentId
          description: Id of parent Dataset
          required: true
          schema:
            type: number
    delete:
      tags:
        - Dataset / Field
      operationId: Delete a Dataset--Field
      description: Disable a Field
      responses:
        '200':
          description: Field deleted successfully
      parameters:
        - in: path
          name: id
          required: true
          description: ''
          schema:
            type: number
        - in: path
          name: parentId
          description: Id of parent Dataset
          required: true
          schema:
            type: number
components:
  parameters: {}
  schemas:
    Dataset--FieldInput:
      type: object
      properties:
        name:
          description: ''
          type: string
        type:
          description: ''
          type: string
          enum: &ref_0
            - STRING
            - NUMERIC
        enumerable:
          description: ''
          type: boolean
        valueCollectionType:
          description: ''
          type: string
          enum: &ref_1
            - SINGLETON
            - SET
            - MULTISET
        values:
          description: ''
          items:
            type: string
          type: array
      required:
        - name
        - type
        - enumerable
        - valueCollectionType
    Dataset--FieldOutput:
      type: object
      properties:
        id:
          description: ''
          type: number
        name:
          description: ''
          type: string
        type:
          description: ''
          type: string
          enum: *ref_0
        enumerable:
          description: ''
          type: boolean
        valueCollectionType:
          description: ''
          type: string
          enum: *ref_1
        values:
          description: ''
          items:
            type: string
          type: array
        enabled:
          description: ''
          type: boolean
        createdAt:
          description: ''
          type: string
          format: ISO8601 UTC date-time
          example: '2019-04-13T03:35:34Z'
        updatedAt:
          description: ''
          type: string
          format: ISO8601 UTC date-time
          example: '2019-04-13T03:35:34Z'
      required:
        - id
        - name
        - type
        - enumerable
        - valueCollectionType
        - createdAt
        - updatedAt
    Dataset--FieldMutable:
      type: object
      properties:
        values:
          description: ''
          items:
            type: string
          type: array
    Dataset--FieldMultiResponse:
      type: object
      properties:
        fields:
          description: Array of retrieved Dataset--Fields
          type: array
          items:
            $ref: '#/components/schemas/Dataset--FieldOutput'
    Error:
      description: 'Error details, only available if there was an issue in processing'
      type: object
      properties:
        httpStatusCode:
          type: number
          description: The integer HTTP error status code for this problem
        errorCode:
          type: string
          description: ' Optional, more granular error code for this problem'
        message:
          type: string
          description: Human readable error message

