// these are all the models we want to generate specs for, and to check
export const allModels = [
    "resourcelike-attribute",
    "authorization",
    "checkrules",
    "complex-resource",
    "direct2dist",
    "distribution",
    "eventing",
    "file",
    "imported-subresources/project_A",
    "linked",
    "milkman",
    "multi",
    "multiplicity",
    "namespaces",
    "optionality",
    "pagination",
    "patchable",
    "request",
    "servers",
    "simple-resource",
    "singleton",
    "stringmaps",
    "table",
    "upversion",
    "polymorphism"
]
