# This build only runs after a push to non-master branches.
steps:
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: node
    entrypoint: yarn
    args: ['test']

timeout: 400s
tags: ['reslang']
