#!/bin/sh

rm -rf /tmp/asyncapi
mkdir /tmp/asyncapi
pbpaste > /tmp/asyncapi-spec.yaml
npx -p @asyncapi/generator ag /tmp/asyncapi-spec.yaml @asyncapi/html-template --output /tmp/asyncapi
open /tmp/asyncapi/index.html
